config:
   UseMetrics: true
   #Avaible EN_en = english; DE_de = german
   Language: EN_en
   useParticles: true
   #Disable Sitting on some furniture
   DisableSitting: false
   viewDistance: 100
   LimitType: PLAYER
   CheckUpdate: true
   Creative:
      RemoveItems: false
      Interact: true
      Place: true
   PlaceMode:
      Mode: "PRIVATE"
      Access: "INTERACT"
   ProtectionLib:
      RegeionMemberAccess: false
   Database:
      type: SQLite
      database: "furniture"
      user: ROOT
      password: 123abcdefg
      port: 3306
      host: localhost
      importCheck: false
   Purge:
      time: 30
      autoPurge: false
      removePurge: false
   timer:
      Enable: false
      time: 300