name: FurnitureLib
version: 0.8.7
description: FurnitureLib
author: Ste3et_C0st
website: http://dicecraft.de
depend: [ProtocolLib]
softdepend: [WorldGuard,PlotMe,Plotz,GriefPrevention,Landlord,LightAPI,PlotSquared,PreciousStones,Residence,Towny,Multiverse,Multiverse-Core,Multiworld,Vault,CoreProtect,DiceChunk]
main: de.Ste3et_C0st.FurnitureLib.main.FurnitureLib
commands: 
  furniture:
    description: Furniture Command
    usage:  /<command>