name: FurnitureLib
version: 1.1
description: FurnitureLib is an Libary to make ArmorStand creations easer
author: Ste3et_C0st
website: http://dicecraft.de
depend: [ProtocolLib]
softdepend: [WorldGuard,LightAPI,Multiverse,Multiverse-Core,Multiworld,Vault]
main: de.Ste3et_C0st.FurnitureLib.main.FurnitureLib
commands: 
  furniture:
    description: Furniture Command
    usage:  /<command>